server:
  port: 9091

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/testdb
    username: sa
    password:
  application:
    name: ORDER-SERVICE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://13.126.4.93:8888/eureka

